import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "../../components/shared/Header";
import "./globals.css";
import Footer from "../../components/shared/Footer";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          {/* You can add additional global <meta> or <link> tags here if needed */}
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-384 m-auto`}
        >
          <Header />

          {/* Wrap app content with MUI AppRouterCacheProvider for SSR caching */}
          <AppRouterCacheProvider>{children}</AppRouterCacheProvider>

          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
